-- MySQL Script generated by MySQL Workbench
-- Mon 30 Nov 2020 09:12:05 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vivino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vivino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vivino` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vivino` ;

-- -----------------------------------------------------
-- Table `vivino`.`acidity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`acidity` (
  `acidity_id` DOUBLE NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`acidity_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`appelations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`appelations` (
  `id` BIGINT NOT NULL,
  `regional_name` TEXT NULL DEFAULT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `interesting_facts` TEXT NULL DEFAULT NULL,
  `country` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`body`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`body` (
  `body_id` DOUBLE NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`body_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`countries` (
  `code` TEXT NOT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `currency` TEXT NULL DEFAULT NULL,
  `regions_count` DOUBLE NULL DEFAULT NULL,
  `users_count` DOUBLE NULL DEFAULT NULL,
  `wines_count` DOUBLE NULL DEFAULT NULL,
  `wineries_count` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`vintages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`vintages` (
  `id` BIGINT NOT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `year` TEXT NULL DEFAULT NULL,
  `wine_id` BIGINT NULL DEFAULT NULL,
  `has_valid_ratings` TINYINT(1) NULL DEFAULT NULL,
  `rating_status` TEXT NULL DEFAULT NULL,
  `ratings_count` BIGINT NULL DEFAULT NULL,
  `ratings_average` DOUBLE NULL DEFAULT NULL,
  `reviews_count` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`critics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`critics` (
  `id` BIGINT NULL DEFAULT NULL,
  `score_normalized` BIGINT NULL DEFAULT NULL,
  `reviewed_at` TEXT NULL DEFAULT NULL,
  `vintage_id` BIGINT NULL DEFAULT NULL,
  INDEX `vintage_id_idx` (`vintage_id` ASC) VISIBLE,
  CONSTRAINT `vintage_id`
    FOREIGN KEY (`vintage_id`)
    REFERENCES `vivino`.`vintages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`grapes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`grapes` (
  `id` BIGINT NOT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `wines_count` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`meat_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`meat_info` (
  `id` BIGINT NOT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `seo_name` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`winery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`winery` (
  `id` BIGINT NOT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `review_status` TEXT NULL DEFAULT NULL,
  `average_rating` DOUBLE NULL DEFAULT NULL,
  `number_of_wines` BIGINT NULL DEFAULT NULL,
  `region` BIGINT NULL DEFAULT NULL,
  `business_name` TEXT NULL DEFAULT NULL,
  `phone` TEXT NULL DEFAULT NULL,
  `email` TEXT NULL DEFAULT NULL,
  `winemaker` TEXT NULL DEFAULT NULL,
  `website` TEXT NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`regions` (
  `region_id` DOUBLE NOT NULL,
  `name_en` TEXT NULL DEFAULT NULL,
  `country` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`region_id`),
  INDEX `country_id_idx` (`country` ASC) VISIBLE,
  CONSTRAINT `country_id`
    FOREIGN KEY (`country`)
    REFERENCES `vivino`.`countries` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`wine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`wine` (
  `vintage_id` BIGINT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `certified_biodynamic` TINYINT(1) NULL DEFAULT NULL,
  `wine_id` BIGINT NOT NULL,
  `wine_name` TEXT NULL DEFAULT NULL,
  `type` TEXT NULL DEFAULT NULL,
  `is_natural` TINYINT(1) NULL DEFAULT NULL,
  `region_id` DOUBLE NULL DEFAULT NULL,
  `country` TEXT NULL DEFAULT NULL,
  `winery_id` BIGINT NULL DEFAULT NULL,
  `rank_percentile_country` DOUBLE NULL DEFAULT NULL,
  `rank_percentile_region` DOUBLE NULL DEFAULT NULL,
  `rank_percentile_winery` DOUBLE NULL DEFAULT NULL,
  `rank_percentile_wine_type` DOUBLE NULL DEFAULT NULL,
  `rank_percentile_global` DOUBLE NULL DEFAULT NULL,
  `wine_description` TEXT NULL DEFAULT NULL,
  `alcohol` DOUBLE NULL DEFAULT NULL,
  `appelation_id` DOUBLE NULL DEFAULT NULL,
  `body_id` DOUBLE NULL DEFAULT NULL,
  `acidity_id` DOUBLE NULL DEFAULT NULL,
  `awards_number` BIGINT NULL DEFAULT NULL,
  `awards_bronze_number` BIGINT NULL DEFAULT NULL,
  `awards_silver_number` BIGINT NULL DEFAULT NULL,
  `awards_gold_number` BIGINT NULL DEFAULT NULL,
  `awards_excellent_number` BIGINT NULL DEFAULT NULL,
  `awards_platinum_number` BIGINT NULL DEFAULT NULL,
  `awards_remarkable_number` BIGINT NULL DEFAULT NULL,
  `awards_commended_number` BIGINT NULL DEFAULT NULL,
  `ratings_distribution_1` BIGINT NULL DEFAULT NULL,
  `ratings_distribution_2` BIGINT NULL DEFAULT NULL,
  `ratings_distribution_3` BIGINT NULL DEFAULT NULL,
  `ratings_distribution_4` BIGINT NULL DEFAULT NULL,
  `ratings_distribution_5` BIGINT NULL DEFAULT NULL,
  `vintage_rank_percentile_country` DOUBLE NULL DEFAULT NULL,
  `vintage_rank_percentile_region` DOUBLE NULL DEFAULT NULL,
  `vintage_rank_percentile_winery` DOUBLE NULL DEFAULT NULL,
  `vintage_rank_percentile_global` DOUBLE NULL DEFAULT NULL,
  `contains_added_sulfites` TINYINT(1) NULL DEFAULT NULL,
  `contains_milk_allergens` TINYINT(1) NULL DEFAULT NULL,
  `contains_egg_allergens` TINYINT(1) NULL DEFAULT NULL,
  `closure` TEXT NULL DEFAULT NULL,
  `year` DOUBLE NULL DEFAULT NULL,
  `median_price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`wine_id`),
  INDEX `vintage_id_idx` (`vintage_id` ASC) VISIBLE,
  INDEX `winery_id_idx` (`winery_id` ASC) VISIBLE,
  INDEX `country_idx` (`country` ASC) VISIBLE,
  INDEX `body_id_idx` (`body_id` ASC) VISIBLE,
  INDEX `acidity_id_idx` (`acidity_id` ASC) VISIBLE,
  INDEX `region_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `vintage_id`
    FOREIGN KEY (`vintage_id`)
    REFERENCES `vivino`.`vintages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `winery_id`
    FOREIGN KEY (`winery_id`)
    REFERENCES `vivino`.`winery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `country`
    FOREIGN KEY (`country`)
    REFERENCES `vivino`.`countries` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `body_id`
    FOREIGN KEY (`body_id`)
    REFERENCES `vivino`.`body` (`body_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `acidity_id`
    FOREIGN KEY (`acidity_id`)
    REFERENCES `vivino`.`acidity` (`acidity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `appelation_id`
    FOREIGN KEY ()
    REFERENCES `vivino`.`appelations` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `region`
    FOREIGN KEY (`region_id`)
    REFERENCES `vivino`.`regions` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`meat_wine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`meat_wine` (
  `wine_id` BIGINT NULL DEFAULT NULL,
  `food_id` BIGINT NULL DEFAULT NULL,
  INDEX `wine_id_idx` (`wine_id` ASC) VISIBLE,
  INDEX `food_idx` (`food_id` ASC) VISIBLE,
  CONSTRAINT `wine_id`
    FOREIGN KEY (`wine_id`)
    REFERENCES `vivino`.`wine` (`vintage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `food`
    FOREIGN KEY (`food_id`)
    REFERENCES `vivino`.`meat_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`merchants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`merchants` (
  `id` BIGINT NOT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `url` TEXT NULL DEFAULT NULL,
  `payments` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`prices` (
  `vintage_id` BIGINT NOT NULL,
  `merchant_id` BIGINT NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `currency` TEXT NULL DEFAULT NULL,
  `bottles_in_stock` DOUBLE NULL DEFAULT NULL,
  `bottles_sold` DOUBLE NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `bottle_volume_ml` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`vintage_id`),
  INDEX `merchant_idx` (`merchant_id` ASC) VISIBLE,
  CONSTRAINT `vintage`
    FOREIGN KEY (`vintage_id`)
    REFERENCES `vivino`.`vintages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `merchant`
    FOREIGN KEY (`merchant_id`)
    REFERENCES `vivino`.`merchants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vivino`.`wine_grapes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivino`.`wine_grapes` (
  `wine_id` BIGINT NULL DEFAULT NULL,
  `grape_id` BIGINT NULL DEFAULT NULL,
  `grapes_share` DOUBLE NULL DEFAULT NULL,
  INDEX `wine_idx` (`wine_id` ASC) VISIBLE,
  INDEX `grapes_idx` (`grape_id` ASC) VISIBLE,
  CONSTRAINT `wine`
    FOREIGN KEY (`wine_id`)
    REFERENCES `vivino`.`wine` (`wine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grapes`
    FOREIGN KEY (`grape_id`)
    REFERENCES `vivino`.`grapes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
